### ISSUE TITLE
using --plot-dir argument leads to distutils.errors.DistutilsInternalError:

### ISSUE THREAD

**Issue by metacoma** [HPENetworking/topology#94]
`$ python3 -m topology --plot-dir=/tmp/ ./my_topology.szn`
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/shitcluster/network/.venv/lib/python3.10/site-packages/topology/__main__.py", line 135, in <module>
    args = parse_args()
  File "/home/ubuntu/shitcluster/network/.venv/lib/python3.10/site-packages/topology/args.py", line 334, in parse_args
    args = validate_args(args)
  File "/home/ubuntu/shitcluster/network/.venv/lib/python3.10/site-packages/topology/args.py", line 210, in validate_args
    mkpath(args.nml_dir)
  File "/usr/lib/python3.10/distutils/dir_util.py", line 32, in mkpath
    raise DistutilsInternalError(
distutils.errors.DistutilsInternalError: mkpath: 'name' must be a string (got None)
```

**Comment by metacoma** [comment]
nevermind, looks like it already fixed in master branch, i will close this issue

**Comment by sergiosmcr** [comment]
Hi @metacoma, Did you notice that the master version does nothing (I mean, no longer makes the actual plot)? 

Are you actually using the topology plots it generates? We thought that most people had the `--plot-dir` in the command but did not actually use the generated plot, so that is why we left it with no implementation as backwards compatibility temporary measure.

**Comment by sergiosmcr** [comment]
We used to rely on [ExtendedNMLManager.save_graphviz()](https://github.com/HPENetworking/pynml/blob/master/lib/pynml/manager.py#L216) to generate the plot depending on the format.You probably are using the default `svg` format. That function generates a graphviz file, then uses graphviz `dot` executable to convert the file to svg, png or any other format.

The way we used that API can be found [here](https://github.com/HPENetworking/topology/commit/4f8d8936900962f2e40ef471ef274adab070aeaf#diff-b3588fca5001397431c42683ee090397483a97abe6ead225b26cf881692e1794L146):
![image](https://user-images.githubusercontent.com/2531700/187271178-70a6a074-4e3b-4676-a882-6f3e85905273.png)

Our assumption was that nobody was using that functionality, do you still want topology to support `--plot-dir`?
Maybe you can try to implement it in a PR? :slightly_smiling_face: The problem is that now we don't use NML, so implementing it is not that easy.

**Comment by metacoma** [comment]
> Our assumption was that nobody was using that functionality, do you still want topology to support --plot-dir?
It's hilarious :) no, just drop it, i'll generate my custom .dot file regarding my L1 network model.

Good luck!
